//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teknik_Servis_Web.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblUrun
    {
        public int ID { get; set; }
        public string AD { get; set; }
        public string MARKA { get; set; }
        public Nullable<decimal> ALIŞFİYAT { get; set; }
        public Nullable<decimal> SATIŞFİYAT { get; set; }
        public Nullable<short> STOK { get; set; }
        public Nullable<byte> KATEGORİ { get; set; }
        public Nullable<bool> DURUM { get; set; }
    }
}
